services:
  - type: web
    name: testlender
    env: python
    plan: free
    buildCommand: pip install -r ./requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
