services:
  - type: web
    name: testlender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
